name: Flask CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest

    # - name: send a mail
    #   uses: dawidd6/action-send-mail@v3
    #   with:
    #       server_address: smtp.gmail.com
    #       server_port: 465
    #       username: ${{ secrets.EMAIL_USERNAME }}
    #       password: ${{ secrets.EMAIL_PASSWORD }}
    #       subject: "GitHub Action Notification"
    #       to: ganeshvjai398@gmail.com
    #       from: ganeshvjai398@gmail.com
    #       body: "This is a test email from GitHub Actions for proof."
    #       convert_markdown: true  # Optional: Convert Markdown to HTML
  
